const express = require('express')
const cors =require('cors')
const app = express()
const {getApi} = require('./controllers/controller')
const artRouter = require('./routes/articles')
const topRouter = require('./routes/topics')
const {notFoundEndpoint,customError,invalidError,internalError, unprocessError} = require('./error-handling/error-handlers')
const userRouter = require('./routes/users')
const comRouter = require('./routes/comments')
app.use(cors())
app.use(express.json())
app.use('/api/articles' , artRouter)
app.use('/api/topics', topRouter)
app.use('/api/users', userRouter)
app.use('/api/comments', comRouter)
//get all endpoints
app.get('/api', getApi)
app.all("/*", notFoundEndpoint)
app.use(unprocessError)
app.use(invalidError)
app.use(customError)
app.use(internalError)
module.exports = app